# Generated by Django 4.1.5 on 2023-01-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='type',
            new_name='_type',
        ),
    ]
