# Generated by Django 4.1.5 on 2023-01-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0002_rename_type_fooditem__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='_type',
            new_name='type_item',
        ),
    ]
