# Generated by Django 4.1.5 on 2023-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0003_rename__type_fooditem_type_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
