# Generated by Django 4.1.5 on 2023-01-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0004_alter_fooditem_carbohydrates_alter_fooditem_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to='calorie_tracker.foodlist'),
        ),
    ]
