# Generated by Django 4.1.5 on 2023-01-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0005_alter_fooditem_type_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='calorie_tracker.foodlist'),
        ),
    ]
