# Generated by Django 4.1.4 on 2023-01-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('sticky', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('last_post_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_thread', to=settings.AUTH_USER_MODEL)),
                ('last_post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_post_thread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
