# Generated by Django 4.1.4 on 2023-01-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
        ('forum', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notify', to='forum.post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_notify', to='forum.thread')),
            ],
            options={
                'index_together': {('thread', 'post')},
            },
            bases=('notifications.notification',),
        ),
    ]
